extends RefCounted
class_name ExamCinematic

static func beats(name: String) -> Array:
	var door := Vector2(200, 430)
	var circle := Vector2(480, 420)
	var student := Vector2(430, 400)
	var griffin_at := Vector2(560, 390)
	var edge := Vector2(140, 440)
	return [
		{"type": "lock"},
		{"type": "fade", "a": 1.0, "sec": 0.05},
		{"type": "spawn_crowd"},
		{"type": "cam_shot", "pos": Vector2(480, 280), "zoom": 0.82, "sec": 0.2},
		{"type": "fade", "a": 0.0, "sec": 0.7},
		{"type": "wait", "sec": 0.35},
		{"type": "say", "speaker": "Grand Summoning Hall", "lines": ["The stands are full. Banners. A circle that has already answered someone today."]},
		{"type": "cam_shot", "pos": Vector2(480, 360), "zoom": 1.05, "sec": 0.8},
		{"type": "say", "speaker": "Instructor", "lines": ["Next candidate. Blood to the seal."]},
		{"type": "cam_shot", "pos": student, "zoom": 1.35, "sec": 0.7},
		{"type": "seal", "on": true, "heat": 1.0},
		{"type": "spark", "at": circle},
		{"type": "say", "speaker": "A Student", "lines": ["The blade. A drop. The runes take it."]},
		{"type": "shake", "amt": 0.12},
		{"type": "spawn_griffin", "at": griffin_at},
		{"type": "cam_shot", "pos": griffin_at, "zoom": 1.45, "sec": 0.6},
		{"type": "react_crowd", "mood": "cheer"},
		{"type": "say", "speaker": "Instructor", "lines": ["Successful pact."]},
		{"type": "cam_shot", "pos": Vector2(480, 300), "zoom": 0.95, "sec": 0.7},
		{"type": "react_crowd", "mood": "cheer"},
		{"type": "say", "speaker": "The Hall", "lines": ["That is what this room is for."]},
		{"type": "say", "speaker": "Instructor", "lines": ["Next candidate.", name + "."]},
		{"type": "cam_shot", "pos": door, "zoom": 1.2, "sec": 0.7},
		{"type": "say", "speaker": "Whispers", "lines": ["Isn't that the one who keeps failing?", "He hasn't summoned anything yet."]},
		{"type": "walk", "who": "ash", "to": circle, "sec": 1.4},
		{"type": "cam_shot", "pos": circle, "zoom": 1.4, "sec": 0.8},
		{"type": "say", "speaker": "Instructor", "lines": ["Blood to the seal."]},
		{"type": "seal", "on": true, "heat": 1.4},
		{"type": "spark", "at": circle},
		{"type": "react_griffin", "mood": "fear"},
		{"type": "say", "speaker": name, "lines": ["Answer my call."]},
		{"type": "shake", "amt": 0.2},
		{"type": "wait", "sec": 0.45},
		{"type": "seal", "on": false},
		{"type": "cam_shot", "pos": circle, "zoom": 1.55, "sec": 0.5},
		{"type": "say", "speaker": "The Circle", "lines": ["Nothing. He is alone in it."]},
		{"type": "react_crowd", "mood": "laugh"},
		{"type": "say", "speaker": "A Student", "lines": ["He can't summon anything."]},
		{"type": "say", "speaker": name, "lines": ["Let me try again."]},
		{"type": "say", "speaker": "Instructor", "lines": ["Ash, the ritual failed."]},
		{"type": "say", "speaker": name, "lines": ["Please. One more time."]},
		{"type": "seal", "on": true, "heat": 2.2},
		{"type": "spark", "at": circle},
		{"type": "shake", "amt": 0.35},
		{"type": "react_griffin", "mood": "fear"},
		{"type": "cam_shot", "pos": Vector2(480, 260), "zoom": 0.88, "sec": 0.8},
		{"type": "say", "speaker": name, "lines": ["ANSWER ME!"]},
		{"type": "wait", "sec": 0.35},
		{"type": "seal", "on": false},
		{"type": "cam_shot", "pos": circle + Vector2(0, 30), "zoom": 1.8, "sec": 0.7},
		{"type": "say", "speaker": "", "lines": ["Blood on the hand. Nothing in the air."]},
		{"type": "cam_shot", "pos": circle, "zoom": 1.65, "sec": 0.5},
		{"type": "say", "speaker": "Instructor", "lines": ["Ash... step out of the circle."]},
		{"type": "walk", "who": "ash", "to": edge, "sec": 1.3},
		{"type": "cam_shot", "pos": edge, "zoom": 1.3, "sec": 0.6},
		{"type": "face", "who": "ash", "dir": Vector2.RIGHT},
		{"type": "cam_shot", "pos": griffin_at, "zoom": 1.5, "sec": 0.7},
		{"type": "react_griffin", "mood": "fear"},
		{"type": "say", "speaker": "", "lines": ["The griffin looks at him. It does not come closer."]},
		{"type": "fade", "a": 1.0, "sec": 0.7},
		{"type": "wait", "sec": 0.25},
		{"type": "fade", "a": 0.0, "sec": 0.4},
		{"type": "unlock"},
	]
